### PR TITLE
feat: docker image

### PR DESCRIPTION
**Pull request by wexder**
Add quick docker image so we can run this inside Truenas as custom app, since adding config to the default exporter app inside custom app was too tedious.
I'm just not sure what method of ci/cd you prefer and where we should publish it and if you even want it here.

### CODE REVIEW

**Comment by Supporterino** [comment]
Thanks for the contribution. I am totally fine with adding a docker image. I am going to add CI and publish it here but can't support much from custom app side, since I am not using TrueNAS apps.

**Comment by Supporterino** [comment]
Image is live here:  `ghcr.io/supporterino/truenas-graphite-to-prometheus:latest`

**Comment by wexder** [comment]
@Supporterino great, it's working nicely. I will try to add some steps how to run it to the readme in following days

**Comment by Supporterino** [comment]
Thanks for also caring about the documentation appreciate your effort

**Pull request merged**
